SistemaClienteTeste/Models/ClienteModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SistemaClienteTeste.Models
{
    public class ClienteModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o CPF do cliente")]
        public string CPF { get; set; }
        [Required(ErrorMessage = "Digite o nome do cliente")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Digite a data de nascimento")]
        public DateTime DataNascimento { get; set; }        
        public string Sexo { get; set; }
        [Required(ErrorMessage = "Digite o Cep")]
        public string Cep { get; set; }       
        public string Logradouro { get; set; }       
        public string Cidade { get; set; }       
        public string UF { get; set; }        
        public DateTime DataCadastro { get; set; }
        public DateTime? DataAtualizacao { get; set; }
    }
}

SistemaClienteTeste/Models/ErrorViewModel.cs
using System;

namespace SistemaClienteTeste.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SistemaClienteTeste/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaClienteTeste.Models;
using SistemaClienteTeste.Repositorio;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SistemaClienteTeste.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IClienteRepositorio _clienteRepositorio;

        public ClienteController(IClienteRepositorio clienteRepositorio)
        {
            _clienteRepositorio = clienteRepositorio; 
        }

        public IActionResult Index()
        {
            List<ClienteModel> clientes =  _clienteRepositorio.BuscarTodos();

            return View(clientes);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            ClienteModel cliente =  _clienteRepositorio.BuscarPorID(id);
            return View(cliente);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            ClienteModel cliente =  _clienteRepositorio.BuscarPorID(id);
            return View(cliente);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado =  _clienteRepositorio.Apagar(id);

                if(apagado) TempData["MensagemSucesso"] = "Cliente apagado com sucesso!"; else TempData["MensagemErro"] = "Ops, não conseguimos cadastrar seu cliente, tente novamante!";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu cliente, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Criar(ClienteModel clienteModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _clienteRepositorio.Adicionar(clienteModel);

                    TempData["MensagemSucesso"] = "Cliente cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(clienteModel);
            }
            catch (Exception erro)
            { 
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu cliente, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Editar(ClienteModel clienteModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    clienteModel =  _clienteRepositorio.Atualizar(clienteModel);
                    TempData["MensagemSucesso"] = "Cliente alterado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(clienteModel);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos atualizar seu cliente, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

SistemaClienteTeste/Controllers/HomeController.cs
using SistemaClienteTeste.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace SistemaClienteTeste.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaClienteTeste/Views/Cliente/ApagarConfirmacao.cshtml
@model ClienteModel
@{
    ViewData["Title"] = "Confirmação apagar cliente";
}

<div class="text-center">
    <h3>Realmente deseja apagar o cliente (@Model.Nome)?</h3>
</div>

<a class="btn btn-primary btn-block" asp-action="Index" asp-controller="Cliente" role="button">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" asp-action="Apagar" asp-controller="Cliente" asp-route-id="@Model.Id" role="button">Confirmar exclusão</a>

SistemaClienteTeste/Views/Cliente/Criar.cshtml
@model ClienteModel
@{
    ViewData["Title"] = "Criar cliente";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar cliente</h1>
</div>

<form asp-controller="Cliente" asp-action="Criar" method="post">

    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="cpf" class="form-label">CPF:</label>
            <input type="text" asp-for="CPF" class="form-control">
            @Html.ValidationMessageFor(x => x.CPF)
        </div>

        <div class="form-group col-md-4">
            <label for="nome" class="form-label">Nome:</label>
            <input type="text" asp-for="Nome" class="form-control">
            @Html.ValidationMessageFor(x => x.Nome)
        </div>

        <div class="form-group col-md-3">
            <label for="data" class="form-label">Data Nascimento:</label>
            <input type="text" asp-for="DataNascimento" class="form-control">
            @Html.ValidationMessageFor(x => x.DataNascimento)
        </div>

        <div class="form-group col-md-3">
            <label for="nome" class="form-label">Sexo:</label>
            <div class="form-check">
                <input class="form-check-input" type="radio" asp-for="Sexo" value="M" checked>
                <label class="form-check-label" for="gridSexoM">
                    Masculino
                </label>

                <input class="form-check-input" type="radio" asp-for="Sexo" value="F" style="margin-left: 10px;">
                <label class="form-check-label" for="gridSexoF" style="margin-left: 28px;">
                    Feminino
                </label>
            </div>

        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="cep" class="form-label">CEP:</label>
            <input type="text" asp-for="Cep" class="form-control" onblur="buscarCep()">
            @Html.ValidationMessageFor(x => x.Cep)
        </div>

        <div class="col-md-4">
            <label for="endereco" class="form-label">Endereço:</label>
            <input type="text" asp-for="Logradouro" class="form-control">
            @Html.ValidationMessageFor(x => x.Logradouro)
        </div>

        <div class="col-md-2">
            <label for="uf" class="form-label">UF:</label>
            <input type="text" asp-for="UF" class="form-control" >
            @Html.ValidationMessageFor(x => x.UF)
        </div>

        <div class="col-md-4">
            <label for="cidade" class="form-label">Cidade:</label>
            <input type="text" asp-for="Cidade" class="form-control" >
            @Html.ValidationMessageFor(x => x.Cidade)
        </div>

    </div>

    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-action="Index" asp-controller="Cliente" role="button">Voltar</a>
</form>

SistemaClienteTeste/Views/Cliente/Editar.cshtml
@model ClienteModel
@{
    ViewData["Title"] = "Editar cliente";
}

<div class="text-center">
    <h1 class="display-4">Alterar cliente</h1>
</div>


<form asp-controller="Cliente" asp-action="Editar" method="post">

    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="cpf" class="form-label">CPF:</label>
            <input type="text" asp-for="CPF" class="form-control">
            @Html.ValidationMessageFor(x => x.CPF)
        </div>

        <div class="form-group col-md-4">
            <label for="nome" class="form-label">Nome:</label>
            <input type="text" asp-for="Nome" class="form-control">
            @Html.ValidationMessageFor(x => x.Nome)
        </div>

        <div class="form-group col-md-3">
            <label for="data" class="form-label">Data Nascimento:</label>
            <input type="text" asp-for="DataNascimento" class="form-control">
            @Html.ValidationMessageFor(x => x.DataNascimento)
        </div>

        <div class="form-group col-md-3">
            <label for="nome" class="form-label">Sexo:</label>
            <div class="form-check">
                <input class="form-check-input" type="radio" asp-for="Sexo" value="M" checked>
                <label class="form-check-label" for="gridSexoM">
                    Masculino
                </label>

                <input class="form-check-input" type="radio" asp-for="Sexo" value="F" style="margin-left: 10px;">
                <label class="form-check-label" for="gridSexoF" style="margin-left: 28px;">
                    Feminino
                </label>
            </div>

        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="cep" class="form-label">CEP:</label>
            <input type="text" asp-for="Cep" class="form-control" onblur="buscarCep()">
            @Html.ValidationMessageFor(x => x.Cep)
        </div>

        <div class="col-md-4">
            <label for="endereco" class="form-label">Endereço:</label>
            <input type="text" asp-for="Logradouro" class="form-control">
            @Html.ValidationMessageFor(x => x.Logradouro)
        </div>

        <div class="col-md-2">
            <label for="uf" class="form-label">UF:</label>
            <input type="text" asp-for="UF" class="form-control">
            @Html.ValidationMessageFor(x => x.UF)
        </div>

        <div class="col-md-4">
            <label for="cidade" class="form-label">Cidade:</label>
            <input type="text" asp-for="Cidade" class="form-control">
            @Html.ValidationMessageFor(x => x.Cidade)
        </div>

    </div>

    <button type="submit" class="btn btn-primary btn-block">Alterar</button>
    <a class="btn btn-secondary btn-block" asp-action="Index" asp-controller="Cliente" role="button">Voltar</a>
</form>

SistemaClienteTeste/Views/Cliente/Index.cshtml
@model List<ClienteModel>
@{
    ViewData["Title"] = "Listagem de Clientes";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" asp-controller="Cliente" asp-action="Criar" role="button">Adicionar novo cliente</a>
    </div>

    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h1 class="display-4">Listagem de clientes</h1>

    <table id="table-cliente" class="display" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">CPF</th>
                <th scope="col">Data Nasc.</th>
                <th scope="col">UF</th>
                <th scope="col">Cidade</th>
                <th scope="col">Sexo</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var cliente in Model)
                {
                    <tr>
                        <th scope="row">@cliente.Id</th>
                        <td>@cliente.Nome</td>
                        <td>@cliente.CPF</td>
                        <td>@cliente.DataNascimento.ToString("dd/MM/yyyy")</td>
                        <td>@cliente.UF</td>
                        <td>@cliente.Cidade</td>
                        <td>@cliente.Sexo</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" asp-action="Editar" asp-controller="Cliente" asp-route-id="@cliente.Id" class="btn btn-primary">Editar</a>
                                <a role="button" asp-action="ApagarConfirmacao" asp-controller="Cliente" asp-route-id="@cliente.Id" class="btn btn-danger">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="7">Nenhum cliente encontrado</td></tr>
            }
        </tbody>
    </table>

</div>

SistemaClienteTeste/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <p>Sistema de controle de Clientes</p>
</div>

SistemaClienteTeste/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Clientes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.4/datatables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Controle de Clientes
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.4/datatables.min.js"></script>
    <script src="~/lib/jquery.mask.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>